### ISSUE TITLE
DOC: No step-by-step instructions to 'Add Gradle Build Steps to rebuild APK packages' section

### ISSUE THREAD

**Issue by cldssty** [firebase/firebaseopensource.com#10]
In the [documentation](https://firebase.google.com/docs/test-lab/continuous#add_revision_control_and_gradle_build_steps), the section that describes how to add Gradle build steps to Jenkins in order to integrate it with revision control systems is not a list of steps that the reader can follow. E.g.

1. From the main page for your project, click Configure.

2. On the project configuration page, scroll down to the Build section, and then choose {insert appropriate build step} from the Add build step menu.

3. and so on

If there are too many steps to list, would it be possible to have links to documentation/examples of how to implement those two items? Thanks!

**Comment by samtstern** [comment]
@cldssty thanks for the feedback but this is the wrong place to file it.  Please use the "Send Feedback" button in the upper-right of the docs:

![image](https://user-images.githubusercontent.com/8466666/39220467-1dc8145c-47e6-11e8-95ec-241795cdf830.png)

**Comment by cldssty** [comment]
Apologies! Will do that instead, thanks.
