### ISSUE TITLE
Typed repositories for Firestore

### ISSUE THREAD

**Issue by Bartinger** [firebase/firebaseopensource.com#102]
[Firestore Storage on Github](https://github.com/freshfox/firestore-storage)

```
npm install firestore-storage
```

We have multiple NodeJS production apps written in Typescript which are heavily based on the Firestore Admin. From that this library was created, since we copied a lot of boilerplate code from each project.

It follows the repository pattern. For each collection you create a repository which provides you with a typed save, delete and multiple querying functions for listing and finding documents.

You can easily replace the "driver" from the default Firestore implementation with an included in-memory implementation for testing. It's also compatible with one of your favorite open source library out there, the dependency injection library [Inversify](https://github.com/inversify).

Since it helped us a lot and saves us a lot of code we made it opens source and published it on npm. Feedback much appreciated

**Comment by samtstern** [comment]
@Bartinger I'd be happy to add this repo to the site!  Just add the `.opensource` configuration to your repo (as explained in the issue template) and then let me know.

**Comment by Bartinger** [comment]
@samtstern Just added the [project.json](https://github.com/freshfox/firestore-storage/blob/master/.opensource/project.json) to the repo. Let me know if you need anything else.

Thanks :)

**Comment by samtstern** [comment]
@Bartinger looks good to me!  Your project should appear on the site in the next 24h

**Comment by Bartinger** [comment]
@samstern just wanted to ask if there's an problem with our repo or the project.json, since it hasn't been published on the site?

**Comment by samtstern** [comment]
@Bartinger this is why they shouldn't let me code alone:
https://github.com/firebase/firebaseopensource.com/commit/12a5084059d850c1218197c10c35a7978e751183

**Comment by samtstern** [comment]
@Bartinger 
https://firebaseopensource.com/projects/freshfox/firestore-storage/

**Comment by Bartinger** [comment]
@samtstern 😆 thank you very much
