### ISSUE TITLE
Adding oddbit/tanam project to listing

### ISSUE THREAD

**Issue by DennisAlund** [firebase/firebaseopensource.com#103]
**Link to project (GitHub)**: https://github.com/oddbit/tanam

**Describe the project in 2-3 sentences**: 
Tanam is a plug-n-play CMS for Firebase that allows you to host and run your own CMS completely free; free as in FOSS and as in free ice cream 🍦

**Why would Firebase developers be interested in this project?**: 
The current landscape CMS for dynamic content sites is dominated by wordpress and static site generators. 

On one hand, WP provides easy to use but a heavy run platform that requires a lot of tweaking to get speedy. It can be quite expensive to just setup a private site with good performance.

The other option is static sites, that perform well but requires the content manager to be comfortable with code editing. Not user friendly.

Tanam is utilizing caching tricks to achieve static site speeds and at the same time strive to provide a easy to use content management interface, similar to what users have in WordPress.

The project is perhaps the first website CMS that is fully built on Firebase. Our mission is to provide a super scalable and more cost effective platform for blogging and other dynamic content sites.

**Stage your project**:

Follow the instructions here and post a link to your staged content:
https://firebaseopensource.com/projects-staging/oddbit/tanam

**Comment by samtstern** [comment]
@DennisAlund sorry the staging server isn't working at the moment but this LGTM!  Will add your project.

**Comment by samtstern** [comment]
@DennisAlund your project should appear on the site in 24h or less.
