### ISSUE TITLE
Consider adding Fireward

### ISSUE THREAD

**Issue by bijoutrouvaille** [firebase/firebaseopensource.com#104]
https://github.com/bijoutrouvaille/fireward

Fireward is a bolt-like language for Firestore that makes rule-writing much more idiomatic and concise. In addition to the rules syntax, it can also output typing files for TypeScript projects.

**Comment by samtstern** [comment]
@bijoutrouvaille Fireward is a really cool project and I'm happy to add it to the site.  You'll need to do a few things:

- Add the `.opensource` folder to your repo with `project.json`, look at some repos already included on the site for examples.
- Possibly reconsider how your README is organized.  The README is where we generate your page from and right now the start of yours is dedicated to the "status" section which might scare people away.  Maybe move that section down on the page?

**Comment by bijoutrouvaille** [comment]
Thanks @samtstern . I have no problems with your suggestions. Just a quick question: what should I put under the `platforms` field? Fireward applies to all platforms, and I only saw specific platforms. How does this look?

```
{
    "name": "Fireward",
    "platforms": [
        "Node",
        "Admin",
        "Web",
        "iOS",
        "Android"
    ],
    "content": "readme.md",
    "related": [ ]
}
```

**Comment by samtstern** [comment]
I'd say it only matters for Android, iOS, and Web since rules don't apply to the admin stuff.

**Comment by bijoutrouvaille** [comment]
Sounds good. I've updated the repo as you asked.

**Comment by samtstern** [comment]
@bijoutrouvaille last thing: it needs to be `project.json` not `package.json`

**Comment by bijoutrouvaille** [comment]
My apologies. Should be fixed now.

**Comment by samtstern** [comment]
https://github.com/firebase/firebaseopensource.com/commit/3f9b326833cf524d2edfe680b7e5289e63f8f2d1

Your page will show up on the site within 24 hours!
