### ISSUE TITLE
Add integrify

### ISSUE THREAD

**Issue by anishkny** [firebase/firebaseopensource.com#106]
**Link to project (GitHub)**: https://github.com/anishkny/integrify

**Describe the project in 2-3 sentences**: `integrify` lets you 🤝 enforce referential and data integrity in Cloud Firestore using triggers. You can `REPLICATE_ATTRIBUTES`, `DELETE_REFERENCES` or `MAINTAIN_COUNT` easily by specifying a JSON config and not having to write code.

**Why would Firebase developers be interested in this project?**: It saves them having to write common snippets of code repeatedly - e.g. updating/deleting denormalized data automatically when the master changes, maintaining a count of "likes" in a document etc.

**Stage your project**: I am blocked from staging my project due to #105. You can see my [`.opensource/project.json`](https://github.com/anishkny/integrify/blob/firebaseopensource/.opensource/project.json).

Follow the instructions here and post a link to your staged content:
https://firebaseopensource.com/projects/firebase/firebaseopensource.com/docs/stage-project.md/

**Comment by samtstern** [comment]
@anishkny thanks for submitting!  You're right, staging is totally broken right now.

**Comment by samtstern** [comment]
Once you submit https://github.com/anishkny/integrify/pull/24 let me know and will add your project.

**Comment by anishkny** [comment]
https://github.com/anishkny/integrify/pull/24 is merged to master. Please add project. Thanks!!!

**Comment by samtstern** [comment]
@anishkny added, your project will show up on the site within 24 hours.

**Comment by samtstern** [comment]
@anishkny we're making a new site similar to firebaseopensource.com but for all of Google. So it would be one place with projects like yours plus projects from Flutter, Angular, Android, etc.

Would it be ok if I included this project on that site? We're hoping to launch in around 2 months so if you're ok with it I'll add your project and send you a link when it's live.

**Comment by anishkny** [comment]
@samtstern of course! Go for it!
