### ISSUE TITLE
Some badges don't show up

### ISSUE THREAD

**Issue by anishkny** [firebase/firebaseopensource.com#108]
**What Happened?**
There are 6 badges on [integrify/README.md](https://github.com/anishkny/integrify/blob/master/README.md) but only 4 are visible on rendered page: https://firebaseopensource.com/projects/anishkny/integrify/

Missing ones seem to be:

```
[![Coverage Status](https://coveralls.io/repos/github/anishkny/integrify/badge.svg?branch=master)](https://coveralls.io/github/anishkny/integrify?branch=master)
[![npm package](https://img.shields.io/npm/v/integrify.svg)](https://www.npmjs.com/package/integrify)
```

**What Did You Expect to Happen**
All badges should show up in rendered page

**Screenshot (If Applicable)**

<img width="669" alt="image" src="https://user-images.githubusercontent.com/357499/57741908-b0bcf180-7673-11e9-88e7-0741cb570fbd.png">
GitHub (correct) ^^^

<img width="896" alt="image" src="https://user-images.githubusercontent.com/357499/57741874-8ff49c00-7673-11e9-8c72-2fc150e57330.png">
FOS (2 missing) ^^^

**Comment by samtstern** [comment]
This is intentional, actually we try to block all badges!  They tend to
clutter up the header and have less meaning off of GitHub.

**Comment by anishkny** [comment]
![Alt Text](https://media.giphy.com/media/psnHfG4auSAxua2dNG/giphy.gif)
