### ISSUE TITLE
Code Highlighting not working 

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebaseopensource.com#109]
**What Happened?**
The code highlighting is not working.

**What Did You Expect to Happen**
In the project site, pages includes some code of any language. It's expected to have code in language specific highlighting. Earlier when I visited this site, I saw code highlighting, but now when I visited, code highlighting was not there. It should be there for more understanding and good UI.

**Screenshot**
<img src="https://user-images.githubusercontent.com/19620536/57794208-c4925180-7760-11e9-9c54-a60b03a1c232.png" height="500"/>

**Comment by samtstern** [comment]
@PatilShreyas I have also noticed this is the case but only on mobile ... not sure what the difference is.

**Comment by samtstern** [comment]
I spoke too soon.  Seems to be broken on desktop now too

**Comment by PatilShreyas** [comment]
Yes... I see..
 I noticed this change long time ago, but raised issue now.
I think something happened wrong in recent PR.
