### ISSUE TITLE
gradle not working

### ISSUE THREAD

**Issue by yashvenrakumar** [firebase/firebaseopensource.com#111]
D/EGL_emulation( 9622): eglMakeCurrent: 0xe167cb80: ver 3 1 (tinfo 0xe7245bd0)
E/eglCodecCommon( 9622): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 9622): glUtilsParamSize: unknow param 0x000082da
I/Choreographer( 9622): Skipped 37 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 9622): eglMakeCurrent: 0xe1585de0: ver 3 1 (tinfo 0xc95e26d0)
I/OpenGLRenderer( 9622): Davey! duration=854ms; Flags=1, IntendedVsync=15729285750035, Vsync=15729902416677, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=15729908522180, AnimationStart=15729908684310, PerformTraversalsStart=15729910558800, DrawStart=15729929193340, SyncQueued=15729933420760, SyncStart=15729937668090, IssueDrawCommandsStart=15729937979270, SwapBuffers=15730022881460, FrameCompleted=15730144897990, DequeueBufferDuration=91049000, QueueBufferDuration=1415000,
D/EGL_emulation( 9622): eglMakeCurrent: 0xe167cb80: ver 3 1 (tinfo 0xe7245bd0)
D/skia    ( 9622): Program linking failed.
I/chatty  ( 9622): uid=10089(com.example.yashvedra) 1.gpu identical 9 lines
D/skia    ( 9622): Program linking failed.
D/skia    ( 9622): Program linking failed.
D/skia    ( 9622): Program linking failed.
E/AndroidRuntime( 9622): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:209)
E/AndroidRuntime( 9622): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.finishWithError(GoogleSignInPlugin.java:386)
E/AndroidRuntime( 9622): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onActivityResult(GoogleSignInPlugin.java:524)
E/AndroidRuntime( 9622): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
E/AndroidRuntime( 9622): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
E/AndroidRuntime( 9622): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 9622): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime( 9622): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime( 9622): 	... 11 more
I/Process ( 9622): Sending signal. PID: 9622 SIG: 9
Lost connection to device.

**Comment by samtstern** [comment]
@yashvenrakumar this does not seem relevant to firebaseopensource.com
