### ISSUE TITLE
GeoFirestore for Android

### ISSUE THREAD

**Issue by Supercaly** [firebase/firebaseopensource.com#112]
**Link to project (GitHub)**: https://github.com/imperiumlabs/GeoFirestore-Android

**Describe the project in 2-3 sentences**: Realtime location queries with Firestore

**Why would Firebase developers be interested in this project?**: If you have the need for querying all Firestore documents geocoded in a given area this is for you.

**Comment by samtstern** [comment]
@Supercaly happy to add this project.  Is it your project?  We need to add a `.opensource/project.json` file to it before it can be added to the website.

**Comment by Supercaly** [comment]
It's not mine, so I'll make a pull request to add it

**Comment by samtstern** [comment]
@Supercaly thanks!  Just let me know when that's done and then I will add the repo to the site.

**Comment by samtstern** [comment]
@Supercaly I am going to close this since it's been a long time and there hasn't been a change.  If you get the config added please let me know!
