### ISSUE TITLE
Add kreait/firebase-php - Admin SDK for PHP

### ISSUE THREAD

**Issue by jeromegamez** [firebase/firebaseopensource.com#116]
Hey there 👋!

I'd be happy and grateful if you were willing to include my project below on the website 🌺

**Link to project (GitHub)**: https://github.com/kreait/firebase-php

**Describe the project in 2-3 sentences**: Similarly to the official Admin SDKs, the unofficial Admin SDK for PHP lets you interact with Firebase from privileged PHP backend server environments. It's not as feature-complete as the official SDKs, but this way, there's always room for improvement 🙂

**Why would Firebase developers be interested in this project?**: There are many PHP developers wanting to integrate their existing PHP applications with Firebase, but not all of them know that this unofficial Admin SDK for PHP exists 😅

**Stage your project**: I'm unable to stage the project to https://firebaseopensource.com/projects-staging/kreait/firebase-php for the same reason as in #105/#106. Here's a link to my [`.opensource/project.json`](https://github.com/kreait/firebase-php/blob/fosdc/.opensource/project.json).

🐙

**Comment by samtstern** [comment]
@jeromegamez thanks for sharing this!  I am happy to add this to the site, but could you change the name of the project to say that it's unofficial?  It's going to show up next to all the official-language Admin SDKs and I want to set the right expectations.

**Comment by jeromegamez** [comment]
@samtstern I just added ` (Unofficial)` to the project.json and updated the project description on https://github.com/kreait/firebase-php to "Unofficial Firebase Admin SDK for PHP", I hope that's ok 🙈

**Comment by samtstern** [comment]
@jeromegamez that's great!  Just move this file (https://github.com/kreait/firebase-php/blob/fosdc/.opensource/project.json) to `master` and we're all set.

**Comment by jeromegamez** [comment]
Done! \o/

**Comment by jeromegamez** [comment]
Thank you so much! 🌺

**Comment by samtstern** [comment]
@jeromegamez here it is:
https://firebaseopensource.com/projects/kreait/firebase-php/

The site republishes every ~24hours so if you make changes to your config or markdown in the future they will be picked up automatically.
