### ISSUE TITLE
Firebase Nuxt

### ISSUE THREAD

**Issue by mustafa-kahraman** [firebase/firebaseopensource.com#117]
**Link to project (GitHub)**: TODO
https://github.com/lupas/nuxt-fire

**Describe the project in 2-3 sentences**: TODO
Firebase for NUXT js
**Why would Firebase developers be interested in this project?**: TODO
cuz VUE js is best!
**Stage your project**:

Follow the instructions here and post a link to your staged content:
https://firebaseopensource.com/projects/firebase/firebaseopensource.com/docs/stage-project.md/

**Comment by samtstern** [comment]
@mustafa-kahraman happy to add your project, please add an `.opensource/project.json` file to that repository so that the site renders properly.  You can look at any other project listed on firebaseopensource.com as an example.

**Comment by mustafa-kahraman** [comment]
@samtstern it is not my project. I am a fun of both firebase and NUXTjs(vuejs). I just offered you to add  NUXT, VUEjs to the list.
Thanks for your reply.

**Comment by samtstern** [comment]
@mustafa-kahraman thanks for the suggestion, I will get it added.

**Comment by samtstern** [comment]
Filed https://github.com/lupas/nuxt-fire/issues/33

**Comment by lupas** [comment]
Created a pull-request for it: https://github.com/firebase/firebaseopensource.com/pull/119
