### ISSUE TITLE
Add Project: geofirestore-js

### ISSUE THREAD

**Issue by MichaelSolati** [firebase/firebaseopensource.com#118]
**Link to project (GitHub)**: https://github.com/geofirestore/geofirestore-js

**Describe the project in 2-3 sentences**: GeoFirestore is an open-source library that extends the Firestore library in order to store and query documents based on their geographic location. At its heart, GeoFirestore is just a wrapper for the Firestore library, exposing many of the same functions and features of Firestore. Its main benefit, however, is the possibility of retrieving only those documents within a given geographic area - all in realtime.

**Why would Firebase developers be interested in this project?**: This library provides geoqueries, much like geofire, to users of Firestore!

**Stage your project**:

Follow the instructions here and post a link to your staged content:
https://firebaseopensource.com/projects/firebase/firebaseopensource.com/docs/stage-project.md/

**Comment by samtstern** [comment]
@MichaelSolati I am happy to add this project but I don't see an `.opensource/project.json` file in the repo?

**Comment by MichaelSolati** [comment]
@samtstern I just realized I needed to do that 😅 (pushed it up)

**Comment by samtstern** [comment]
@MichaelSolati your project should appear on the site within 24h!

**Comment by MichaelSolati** [comment]
@samtstern just wanted to mention that I haven't seen it yet on the site... Did I configure something incorrectly?

**Comment by samtstern** [comment]
@MichaelSolati good catch the build had been broken for days!
https://firebaseopensource.com/projects/geofirestore/geofirestore-js/
