### ISSUE TITLE
Add Project: Flamelink JS SDK

### ISSUE THREAD

**Issue by gitdubz** [firebase/firebaseopensource.com#120]
**Link to project (GitHub)**: https://github.com/flamelink/flamelink-js-sdk

**Describe the project in 2-3 sentences**: Official JS SDK for Flamelink (a firebase CMS). The project aims to help developers work with the underlying data structures which are created when using Flamelink.

**Why would Firebase developers be interested in this project?**: The project simplifies working with the data structures created using Flamelink. It speeds up development time and abstracts complex relational data functions so that users don't have to concern themselves with it.

**Comment by gitdubz** [comment]
@samtstern I have updated the repo,  thanks for your help!

**Comment by samtstern** [comment]
LGTM!

**Comment by samtstern** [comment]
@gitdubz expect the project to appear on the site in the next 24h
