### ISSUE TITLE
Consider adding Svarog CLI to the list

### ISSUE THREAD

**Issue by dantothefuture** [firebase/firebaseopensource.com#121]
**Link to project (GitHub)**:
[dantothefuture/svarog](https://github.com/dantothefuture/svarog)

**Describe the project in 2-3 sentences**:
Svarog is a CLI that generates schema validators for Firestore from JSON Schema files. The output is a single universal function `isValid($id: string): boolean` that you can use anywhere in your security rules to prevent unwanted mutations.

**Why would Firebase developers be interested in this project?**:
Schemaless design can be both an advantage and a disadvantage - and when it's the latter, devs have to write a ton of hardly readable CEL code to make sure their database schema is protected. That's where Svarog comes in, allowing Firebase developers to generate structure validators from a familiar, platform-agnostic JSON Schema format.

I know this is a shameless plug but maybe it's worth a try who knows 🙂

**Comment by samtstern** [comment]
@dantothefuture that's a really cool project!  If you add a `.opensource/project.json` file to your repo I am happy to add it to this site.

**Comment by samtstern** [comment]
Oh wait it's already there.  In that case will add now.

**Comment by samtstern** [comment]
Will be live within 24h, let me know if that's not the case.

**Comment by samtstern** [comment]
@dantothefuture lookin' good:
https://firebaseopensource.com/projects/dantothefuture/svarog/

**Comment by dantothefuture** [comment]
Wow that was quick! Thanks @samtstern 🙂

**Comment by samtstern** [comment]
@dantothefuture no problem thanks for the awesome tool!  I also shared it on our team chat.  We're always looking for new ways to make Security Rules better.
