### ISSUE TITLE
Firegraph - GraphQL Superpowers for Firestore

### ISSUE THREAD

**Issue by sejr** [firebase/firebaseopensource.com#122]
**Link to project (GitHub)**: https://github.com/sejr/firegraph

**Describe the project in 2-3 sentences**: Firegraph allows you to run GraphQL queries against a Firestore instance. Fetch related data (e.g. references, subcollections) and have a well-structured response ready for usage in your app immediately.

**Why would Firebase developers be interested in this project?**: Firegraph helps developers execute complex Firestore queries in a more expressive way. As the project moves forward, I hope to incorporate real-time queries, caching, mutations, and more. I would love for other Firestore users to help me maintain it.

**Comment by samtstern** [comment]
@sejr so sorry don't know how I missed this!  Just add `.opensource/project.json` to your project and I am happy to add this to the site.

**Comment by samtstern** [comment]
@sejr do you still want to add this repo to the site?  If so please add the missing config file!  If you need a good example look at the one in the Emberfire repo.

**Comment by sejr** [comment]
@samtstern Added!

**Comment by samtstern** [comment]
@sejr added your project to the site!  You should see it appear in the next 24 hours in the 'web' section.
