### ISSUE TITLE
ioa

### ISSUE THREAD

**Issue by MichaelRCruz** [firebase/firebaseopensource.com#123]
**Link to project (GitHub)**: 
https://github.com/MichaelRCruz/ioa
**Describe the project in 2-3 sentences**: 
A minimal, fully featured chat app in Firebase & React 16.8. Runs on Realtime Database and supports markdown.

**Why would Firebase developers be interested in this project?**: 
The new Firebase Extensions would be a great next step for this project. Given the latest release, this would be a nice place to develop all Firebase features old _and_ new. Additionally, it would provide more fun because we could pretend we're in the movie, [Contact](https://www.youtube.com/watch?v=d9C2cF3KvP8), since [reactfire](https://github.com/FirebaseExtended/reactfire/tree/master/reactfire).

**Comment by samtstern** [comment]
@MichaelRCruz looks great to me!  I added this to the config and you should see your project appear within 24 houts.

**Comment by samtstern** [comment]
I would suggest improving the README of that repo to be more descriptive since that's what will be used to generate your page on firebaseopensource, add some text describing what's in the repo and what Firebase developers can learn from it.

**Comment by MichaelRCruz** [comment]
@samtstern great idea! Writing now.
