### ISSUE TITLE
Add Project: generator-react-firebase

### ISSUE THREAD

**Issue by prescottprue** [firebase/firebaseopensource.com#124]
**Link to project (GitHub)**
[generator-react-firebase](https://github.com/prescottprue/generator-react-firebase)

**Describe the project in 2-3 sentences**
Generator for starting projects using React and Firebase (Redux optional). Has options for including cloud messaging, analytics functions, tests and more. Also includes sub-generators for scaffolding Routes + React Components + Cloud Functions within existing projects.

**Why would Firebase developers be interested in this project?**
Start a new React + Firebase project with a single command. Has options for including features such as cloud messaging, analytics, functions, tests and more. There are also commands (called sub-generators) for scaffolding routes, React components, and cloud functions. Built using [Yeoman](https://yeoman.io/) (popular generator framework).

**Comment by samtstern** [comment]
@prescottprue same as #125, just add the config and I will definitely add this project.

**Comment by samtstern** [comment]
@prescottprue a few things:

1. `related` should only be other projects that are on firebaseopensource.com
2. `tabs` should be objects, see [this example](https://github.com/firebase/emberfire/blob/master/.opensource/project.json#L19)

**Comment by samtstern** [comment]
Sorry for the delay here too, added the project!
