### ISSUE TITLE
Add Project: redux-firestore

### ISSUE THREAD

**Issue by prescottprue** [firebase/firebaseopensource.com#125]
**Link to project (GitHub)**
[redux-firestore](https://github.com/prescottprue/react-redux-firebase)

**Describe the project in 2-3 sentences**
Redux bindings for Firestore. Integrates with [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) for  for React Hooks and Higher Order Components.

**Why would Firebase developers be interested in this project?**
Standardizes redux actions/reducers for common Firestore interactions. Does not require react, but integrates with [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) for React Hooks and Higher Order Components.

**Comment by samtstern** [comment]
@prescottprue sounds great!  Just add `.opensource/project.json` to your project and I'm happy to add it.

**Comment by prescottprue** [comment]
Added for both, thanks!

**Comment by samtstern** [comment]
Sorry for the huge delay here!  I was confused because your post actually links to `react-redux-firebase` not `redux-firestore` and I kept clicking the link and not seeing the required `json` file.
