### ISSUE TITLE
Project routing needs to be case insensitive

### ISSUE THREAD

**Issue by samtstern** [firebase/firebaseopensource.com#130]
**What Happened?**
Tried to go to this page (clicked from the release notes section of the homepage);
https://firebaseopensource.com/projects/IjzerenHein/firestorter/

**What Did You Expect to Happen**
Expected to end up here:
https://firebaseopensource.com/projects/ijzerenhein/firestorter/

**Screenshot (If Applicable)**
Page loads forever...

**Comment by lupas** [comment]
@samtstern 

This has been fixed with the already merged https://github.com/firebase/firebaseopensource.com/pull/151

**Comment by rosariopfernandes** [comment]
@lupas I'm not sure about that. I tried to go to the page linked above and it displays a blank page.

**Comment by lupas** [comment]
@rosariopfernandes 
The new version is not yet deployed, did you try it on localhost or on firebaseopensource.com?

**Comment by samtstern** [comment]
I actually did deploy the new version today but I think there are some
lingering issues with routing within a project.

This message will appear in Issue #413 of "Don't deploy code right before
you get on an airplane"

**Comment by samtstern** [comment]
Yep it works now, thank you!
