### ISSUE TITLE
Add Project: FCM-OnDeviceNotificationScheduler

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebaseopensource.com#133]
**Link to project (GitHub)**: https://github.com/PatilShreyas/FCM-OnDeviceNotificationScheduler

**Describe the project in 2-3 sentences**: 
This project contains the implementation of scheduling FCM Push Notification on the device. What is does is - Whenever FCM Data payload is received, it parses it and sets One-time non-repeating Alarm using `AlarmManager`. When Alarm is triggered, `WorkManager` is used to execute background running task and at a specified time, Notification is displayed on the system tray. If the payload is received and Internet Connectivity is OFF, still notification can be displayed.

**Why would Firebase developers be interested in this project?**: 
There are other methods like ***Google Cloud Pub/Sub*** and ***Cron Jobs*** to perform such tasks. But these are costly solutions to implement. By using this method, it makes easy and useful to schedule in a device.
 **Advantage**  : Notification can be displayed when Internet/Wi-Fi is OFF.

**Comment by samtstern** [comment]
@PatilShreyas hey sorry I somehow missed this one!  Can you add a `.opensource/project.json` file to your repo?  Then I am happy to add this.

If you're not sure what that looks like, look at any other repo that's part of firebaseopensource.com

**Comment by PatilShreyas** [comment]
I've set up repository and opened PR #136 for this.

**Comment by samtstern** [comment]
Fixed by #136
