### ISSUE TITLE
Firebase realtime database assistant

### ISSUE THREAD

**Issue by Im-Mark42** [firebase/firebaseopensource.com#137]
**Link to project (GitHub)**: https://github.com/Im-Mark42/FirebaseDatabaseAssistant

**Describe the project in 2-3 sentences**: 
In this project, I implemented an `assistant` for Firebase Realtime Database. User just need to create a Repository class, extends it with `DatabaseRepo<T>` class and provide a Model class in case of `T` i.e `DatabaseRepo<User>`. Then he/she can do all the Firebase realtime database operations. i.e read, write, update, delete.

**Why would Firebase developers be interested in this project?**:
It's interesting because no need to write any firebase code inside `Activity` or `Fragment`, all the firebase code will be available in the Repository class. Purely base on MVVM so that user have unique Repository class for all Model class. Also use `LiveData<T>` to provide information, because all the networking function are Async function.

**Comment by samtstern** [comment]
@Im-Mark42 thanks for the suggestion!

A few things:

  1. Could you add an `.opensource/project.json` file to your project?  Look at any other project featured on firebaseopensource.com as an example
  2. I would suggest not publishing your code in the `com.firebase.*` package.  That can be misleading to developers and you will be unable to ever publish on Maven Central or Bintray, where we own the `com.firebase` org.

**Comment by Im-Mark42** [comment]
@samtstern thanks for the suggestion

1. added `.opensource/project.json` file.
2. change `com.firebase.*` to a different package name.

**Comment by samtstern** [comment]
@Im-Mark42 thanks!  I sent a PR to fix a small issue in your config:
https://github.com/Im-Mark42/FirebaseDatabaseAssistant/pull/3

But I will add your project to the site now.

**Comment by Im-Mark42** [comment]
@samtstern Thanks a lot!. I merge the PR
