### ISSUE TITLE
Firebase Firestore Assistant

### ISSUE THREAD

**Issue by Im-Mark42** [firebase/firebaseopensource.com#138]
**Link to project (GitHub)**: https://github.com/Im-Mark42/FirebaseFirestoreAssistant

**Describe the project in 2-3 sentences**: 
In this project, I implemented an `assistant` for Firebase Firestore. User just need to create a Repository class, extends it with `FirestoreRepo<T>` class and provide a Model class in case of `T` i.e `FirestoreRepo<User>`. Then he/she can do all the Firebase Firestore operations. i.e read, write, update, delete.

**Why would Firebase developers be interested in this project?**: TODO
It's interesting because no need to write any firebase code inside `Activity` or `Fragment`, all the firebase code will be available in the Repository class. Purely base on MVVM so that user have unique Repository class for all Model class. Also use `LiveData<T>` to provide information, because all the networking function are Async function.

**Comment by samtstern** [comment]
Added (https://github.com/firebase/firebaseopensource.com/commit/c44caf0ea6102c96378880e6cc52490a1ac3c531) thank you!
