### ISSUE TITLE
Add rosariopfernandes/firecoil

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebaseopensource.com#140]
**Link to project (GitHub)**: https://github.com/rosariopfernandes/firecoil

**Describe the project in 2-3 sentences**: firecoil makes it easier to load images from Cloud Storage in an Android App, through a StorageReference, using the image loading library [Coil](github.com/coil-kt/coil).

**Why would Firebase developers be interested in this project?**: Loading images with firecoil is as simple as:
```kotlin
val imageView: ImageView = ...
val storageRef: StorageReference = ...

imageView.load(storageRef)
```

**Comment by samtstern** [comment]
@rosariopfernandes that's awesome!  It's like `firebase-ui-storage` but using Kotlin to be way smoother.

Just add `.opensource/project.json` to your project repo and I will happily add it to the site.

**Comment by rosariopfernandes** [comment]
@samtstern Yes! :) Just added the `project.json` file

**Comment by rosariopfernandes** [comment]
@samtstern Thanks!
