### ISSUE TITLE
Covid19Co.org  - want to help people in Colombia to overcome this situation

### ISSUE THREAD

**Issue by estebance** [firebase/firebaseopensource.com#154]
**Link to project (GitHub)**:

https://github.com/CovidCo/covidco-web-app
https://github.com/CovidCo/Covid-Co-API

**Describe the project in 2-3 sentences**:

We want to help people identify the symptoms of Coronavirus and contact their health provider or receive an initial diagnosis from a doctor. 

**Why would Firebase developers be interested in this project?**: You  probably are going to save  people

**Comment by samtstern** [comment]
@estebance thanks for posting and 👍 for using your skills for good.

Is this a website or tools for people to build their own website?  I ask because firebaseopensource.com is not a showcase for cool things built on Firebase, it's a showcase of tools for Firebase developers.

**Comment by samtstern** [comment]
@estebance ok I have looked at the site and while I think it's definitely useful (great work!) it doesn't belong on firebaseopensource.com which is a showcase of tools for Firebase developers.

Good luck and stay safe!
