### ISSUE TITLE
Code highlighting seems broken

### ISSUE THREAD

**Issue by samtstern** [firebase/firebaseopensource.com#155]
**What Happened?**
Navigate to:
https://firebaseopensource.com/projects/firebase/firebaseui-android/auth/readme

No code highlighting

**What Did You Expect to Happen**
Code highlighting

**Screenshot (If Applicable)**
<img width="1095" alt="Screen Shot 2020-03-26 at 3 55 39 PM" src="https://user-images.githubusercontent.com/8466666/77690859-53bfe680-6f7a-11ea-85fe-4f070230ab4d.png">

**Comment by samtstern** [comment]
@lupas any idea about this one?  In Chrome it seems to flicker in and out for me, in Safari I never see the highlighting.

**Comment by lupas** [comment]
@samtstern 
Didn't really change anything specifically to that, but maybe due to the changes in the styles something broke.

I'll have a look at it tomorrow.

**Comment by samtstern** [comment]
Should be fixed by #156

**Comment by lupas** [comment]
@samtstern 
Just found out that it does not entirely fix the issue. But it makes it a lot better at least.

Main problem now is that since this is a SPA (or at least the routing behaves like one) we don't reload on page change, and so `code-prettify` doesn't run on the new route. E.g. when jumping from the list to the project page. 

On reload it works now (most of the time, still a bit unreliable honestly), but not on routing.

I wonder if there is a cleaner solution that does not require us (1) rewrite the classes in a cloud function (2) not need to load this script...

Isn't there a simple CSS bases solution?

**Comment by samtstern** [comment]
👍 

The JS transforms
```html
<pre class="prettyprint>
  // .. code
```

Into something like this, at which point CSS takes over:
```html
<pre class="" translate="no" dir="ltr" is-upgraded=""><span class="pln">doc_ref </span><span class="pun">=</span><span class="pln"> db</span><span class="pun">.</span><span class="pln">collection</span><span class="pun">(</span><span class="pln">u</span><span class="str">'cities'</span><span class="pun">).</span><span class="pln">document</span><span class="pun">(</span><span class="pln">u</span><span class="str">'SF'</span><span class="pun">)</span><span class="pln"><br><br></span><span class="kwd">try</span><span class="pun">:</span><span class="pln"><br>&nbsp; &nbsp; doc </span><span class="pun">=</span><span class="pln"> doc_ref</span><span class="pun">.</span><span class="kwd">get</span><span class="pun">()</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="kwd">print</span><span class="pun">(</span><span class="pln">u</span><span class="str">'Document data: {}'</span><span class="pun">.</span><span class="pln">format</span><span class="pun">(</span><span class="pln">doc</span><span class="pun">.</span><span class="pln">to_dict</span><span class="pun">()))</span><span class="pln"><br></span><span class="kwd">except</span><span class="pln"> google</span><span class="pun">.</span><span class="pln">cloud</span><span class="pun">.</span><span class="pln">exceptions</span><span class="pun">.</span><span class="typ">NotFound</span><span class="pun">:</span><span class="pln"><br>&nbsp; &nbsp; </span><span class="kwd">print</span><span class="pun">(</span><span class="pln">u</span><span class="str">'No such document!'</span><span class="pun">)</span><div class="devsite-github-link nocode no-select"><a href="https://github.com/GoogleCloudPlatform/python-docs-samples/blob/f358fbe3bc67bf83f350ca119c38c4c81b348bde/firestore/cloud-client/snippets.py#L218-L224" class="gc-analytics-event">snippets.py</a></div><span class="pln"><br></span></pre>
```

We could look into ways to do this transformation server-side though when generating the HTML from the MD.

**Comment by lupas** [comment]
> We could look into ways to do this transformation server-side though when generating the HTML from the MD.

Doing it server-side (in the cloud function) would be the most performant and reliable way to do it, yes. Not sure if code-prettify works well on NodeJs tho, but I'm sure there's a way.

For not at least https://github.com/firebase/firebaseopensource.com/pull/157 fixes the issues mentioned above.

**Comment by samtstern** [comment]
#157 works great!  Just deployed.  Thanks so much for figuring that out!
