### ISSUE TITLE
[Feature] Implement Nuxt' full-static mode

### ISSUE THREAD

**Issue by lupas** [firebase/firebaseopensource.com#170]
**What Happened?**
Nuxt 2.13.0 was released!
Read here: https://nuxtjs.org/blog/going-full-static

**What Did You Expect to Happen**
Fulls static mode will be available with Nuxt v2.13.0.

**Screenshot (If Applicable)**
Nope, but:

Nuxt just released 2.13.0 which now includes a full static mode, meaning:
-> No more additional external calls to Firestore on route changes.
-> blazing fast pre-rendered html without page-reloads

As you remember @samtstern, we changed all the `<nuxt-link/>`'s back to `<a/>` so we won't reload data from Firestore on each route change. With the new Nuxt version and full-static mode that won't happen anymore, see article linked above.

So this issue is here for your information about that, and at some point when we have some spare time we can implement that for that project:

- [ ] Implement full-static mode as described in the article
- [ ] Switch `<a/>` links back to `<nuxt-link/>`

best regards

**Comment by samtstern** [comment]
That's so cool!  I'm gonna try that right now.

**Comment by samtstern** [comment]
https://github.com/firebase/firebaseopensource.com/pull/171
