### ISSUE TITLE
[WIP] FireSource: Apollo Server data source wrapping Firestore REST APIs

### ISSUE THREAD

**Issue by devskope** [firebase/firebaseopensource.com#172]
**Link to project (GitHub)**:  https://github.com/devskope/apollo-firesource 

**Describe the project in 2-3 sentences**:  Apollo GraphQL Server data source wrapping Firestore REST APIs. Implemented in Typescript

**Why would Firebase developers be interested in this project?**: Conveniently use Firestore as a data source in GraphQl projects

**Comment by samtstern** [comment]
@devskope pretty cool!  Happy to add it to the site.  Just add a `.opensource/config.json` file to your repo so that we can display it properly. If you need an example just look at any other project that's featured on firebaseopensource.com

**Comment by devskope** [comment]
`.opensource/project.json`  added

**Comment by samtstern** [comment]
@devskope looks great, thank you!  Unfortunately we only support pulling down the `master` branch of each repo right now and it looks like you're on the `develop` branch by default.

If you add the JSON file to your `master` branch as well then I can add your project to the site.

**Comment by devskope** [comment]
I believe It's in order now @samtstern.

**Comment by samtstern** [comment]
@devskope thanks, looks great!  Your project will appear on the site within 24 hours.

**Comment by samtstern** [comment]
The build was broken for a few days but your project is now live here:
https://firebaseopensource.com/projects/devskope/apollo-firesource/
