### ISSUE TITLE
Fladle - Easily Scale Android Instrumentation Tests with Firebase Test Lab

### ISSUE THREAD

**Issue by runningcode** [firebase/firebaseopensource.com#173]
**Link to project (GitHub)**: https://github.com/runningcode/fladle

**Describe the project in 2-3 sentences**: Fladle makes it easy to run and scale your Android Instrumentation Tests on Firebase Test Lab. Run all your Android Instrumentation tests on Firebase Test lab with a few lines of configuration and a simple Gradle task. For larger projects, Fladle also supports sharding and merging tests reports.

**Why would Firebase developers be interested in this project?**: The plugin makes it much easier to configure and launch tests on firebase by taking care of the heavy lifting. Fladle is used by well known software engineering companies like Salesforce, SoundCloud, Robinhood, Instacart, Dropbox and more.

**Comment by samtstern** [comment]
@runningcode I would be happy to add Fladle to the site!  It's such a good piece of software.  We just need to add an `.opensource/project.json` file to the Flade repo.  Check out other projects which are on firebaseopensource.com for examples of the file format.

**Comment by runningcode** [comment]
Awesome. Will do. How does that json file handle mkdocs? https://runningcode.github.io/fladle/
I couldn't find an example of how to link mkdocs hosted documentation to that.
Also is there a list of all possible configuration options for `.opensource/project.json`?

**Comment by samtstern** [comment]
@runningcode yeah sorry my documentation is super lacking!  I think a good example to follow is Emberfire:
https://github.com/firebase/emberfire/blob/master/.opensource/project.json

We natively support any markdown files that live on Github as `pages`.  If you want to link to your own docsite you'd do that under `tabs`.

**Comment by runningcode** [comment]
Sorry it took me a while. It's been added: https://github.com/runningcode/fladle/blob/master/.opensource/project.json
Let me know if anything is missing or if there are any properties to add that would make it work better. Cheers.

**Comment by samtstern** [comment]
@runningcode thanks!  Your page should appear on the site within 24h
