### ISSUE TITLE
Firestore Export & Import Project

### ISSUE THREAD

**Issue by dalenguyen** [firebase/firebaseopensource.com#174]
**Link to project (GitHub)**: TODO

https://github.com/dalenguyen/firestore-backup-restore

**Describe the project in 2-3 sentences**: TODO

This project will help to export & import database from Cloud Firestore through an NPM package.

**Why would Firebase developers be interested in this project?**: TODO

The current option for backup & restore the database from Cloud Firestore is done through `gcloud` command. The project can help people integrate the export and import feature to their Nodejs / Javascript project. This is not perfect yet, and with the help of the developer community, this project can be improved tremendously.

**Comment by samtstern** [comment]
@dalenguyen nice!  I am happy to add this to the site.  Just add an `.opensource/project.json` file to your repo and then I can add you.  If you need examples check out some of the repos which are already featured on the site like this one:
https://github.com/firebase/emberfire/blob/master/.opensource/project.json

**Comment by dalenguyen** [comment]
Thank @samtstern, I added the project.json file. Let me know there is anything that I can revise.

https://github.com/dalenguyen/firestore-backup-restore/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
@dalenguyen added!  Thanks for creating these tools for the Firebase Community!

**Comment by samtstern** [comment]
The build on the site was broken for a few days, sorry!  It's fixed now and your site is live here:
https://firebaseopensource.com/projects/dalenguyen/firestore-backup-restore/

**Comment by dalenguyen** [comment]
Awesome. Thank @samtstern :D
