### ISSUE TITLE
pages removed from project.json are still being generated

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebaseopensource.com#176]
**What Happened?**
The `.opensource/project.json` file in [rosariopfernandes/fireXtensions](https://github.com/rosariopfernandes/fireXtensions/) used to contain:
```json
  "pages" : {
    "tutorials/realtime-database.md": "Realtime Database Tutorial",
    "tutorials/cloud-firestore.md": "Cloud Firestore Tutorial"
  },
```

But now it has been changed to:
```json
  "pages" : {
    "docs/analytics.md": "Analytics fireXtensions"
  },
```

And I can see that the `tutorials/cloud-firestore.md` page is still being created by the site and it's available at this url: https://firebaseopensource.com/projects/rosariopfernandes/firextensions/tutorials/cloud-firestore/

**What Did You Expect to Happen**
Expected `cloud-firestore.md` to not be generated, since it is no longer in the project.json file.

**Screenshot (If Applicable)**

**Comment by samtstern** [comment]
@rosariopfernandes thanks for noticing this!  That's a good callout.  I've also noticed that projects which have been renamed never get "deleted" from their old location.  So I think I'll have to make the functions that do all the scraping be a little more strict.
