### ISSUE TITLE
This is an open source project for Cloud Firestore.

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebaseopensource.com#181]
**Link to project (GitHub)**: https://github.com/1amageek/Ballcap-iOS

**Describe the project in 2-3 sentences**: Ballcap is a database schema design framework for Cloud Firestore

**Why would Firebase developers be interested in this project?**: Cloud Firestore is a great schema-less and flexible database that can handle data. However, its flexibility can create many bugs in development. Ballcap can assign schemas to Cloud Firestore to visualize data structures. This plays a very important role when developing as a team.

**Have you added a `.opensource/project.json` file to your site**: YES

Examples:
 - https://github.com/invertase/react-native-firebase/blob/master/.opensource/project.json
 - https://github.com/sgarciac/fuego/blob/master/.opensource/project.json
 - https://github.com/firebase/emberfire/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
I believe this has already been addressed in another issue, so closing this.  Thanks for adding your project!
