### ISSUE TITLE
[Flutter Library] Flamingo

### ISSUE THREAD

**Issue by hukusuke1007** [firebase/firebaseopensource.com#183]
**Link to project (GitHub)**: 
https://github.com/hukusuke1007/flamingo

**Describe the project in 2-3 sentences**: 
This is Firebase Firestore Model Framework Library for Flutter.
Can be manage document reference and collection reference. And provide Firestore and Cloud Storage wrap interface.

**Why would Firebase developers be interested in this project?**
Can be created safely Firestore Model like a Ballcap-iOS. 
Can be used field data key of enum and accessed to Firestore data.
Can be managed safely Firestore references(collection reference and document reference).
etc...

**Have you added a `.opensource/project.json` file to your site**: Yes
https://github.com/hukusuke1007/flamingo/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
Love the project and the name, added!
https://github.com/firebase/firebaseopensource.com/commit/13ed5c09f0da26149badbfb16e3a97f881908e58

**Comment by samtstern** [comment]
@hukusuke1007 we're making a new site similar to firebaseopensource.com but for all of Google. So it would be one place with projects like yours plus projects from Flutter, Angular, Android, etc.

Would it be ok if I included this project on that site? We're hoping to launch in around 2 months so if you're ok with it I'll add your project and send you a link when it's live.

**Comment by hukusuke1007** [comment]
@samtstern OK.  Please added a Flamingo in your site. Thank you.
