### ISSUE TITLE
Addition of Flank firebaseopensource.com

### ISSUE THREAD

**Issue by Sloox** [firebase/firebaseopensource.com#184]
**Link to project (GitHub)**: https://github.com/Flank

**Describe the project in 2-3 sentences**: 
Flank is a massively parallel Android and iOS test runner for Firebase Test Lab. Flank is YAML compatible with the gcloud CLI and has extra features for performance and stability.

**Why would Firebase developers be interested in this project?**: 
Flank provides testing features to accelerate velocity and quality.

**Have you added a `.opensource/project.json` file to your site**: Yes
https://github.com/Flank/flank/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
@Sloox looks great I am happy to add it to the site!  I sent a PR to update the `project.json` a bit:
https://github.com/Flank/flank/pull/981

**Comment by samtstern** [comment]
Added it to the site!

**Comment by Sloox** [comment]
@samtstern thanks merged your changes

**Comment by samtstern** [comment]
@Sloox thanks!  You should see your page on the site within 24 hours.
