### ISSUE TITLE
Add Project cypress-firebase

### ISSUE THREAD

**Issue by prescottprue** [firebase/firebaseopensource.com#185]
**Link to project (GitHub)**: [cypress-firebase](https://github.com/prescottprue/cypress-firebase)

**Describe the project in 2-3 sentences**: 

Cypress commands and plugin to simplify testing Firebase projects. Has support for Auth, Firestore, and Real Time Database.

**Why would Firebase developers be interested in this project?**: Drastically simplifies using Cypress to interact with Firebase allowing the developer to focus on testing app features.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by samtstern** [comment]
@prescottprue nice!  I have been looking into Cypress for some of my own sites.
