### ISSUE TITLE
electron-firebase

### ISSUE THREAD

**Issue by david-asher** [firebase/firebaseopensource.com#189]
**Link to project (GitHub)**: https://github.com/david-asher/electron-firebase

**Describe the project in 2-3 sentences**: Electron-Firebase is a quickstart framework for building cross-platform cloud-connected desktop applications using Electron and Firebase. With a few configuration settings you can include a complete authentication workflow into your app that can use email/password, phone number, google, facebook, or many other identity providers.

**Why would Firebase developers be interested in this project?**: Electron-Firebase is unusual in being both an NPM module and an example application, and it spans both worlds of the Browser JavaScript environment and the host node.js environment. As such, it will install several folders and files into the root of the NPM application that form the example application, which you are encouraged to modify for your own purposes.

**Have you added a `.opensource/project.json` file to your site**: Yes
 - https://github.com/david-asher/electron-firebase/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
@david-asher looks really cool!  Let me add it to the site now.  I hope those `.js.md` files don't trip up the script!

**Comment by samtstern** [comment]
Your page should be live on the site within 24h

**Comment by samtstern** [comment]
@david-asher we're making a new site similar to firebaseopensource.com but for all of Google. So it would be one place with projects like yours plus projects from Flutter, Angular, Android, etc.

Would it be ok if I included this project on that site? We're hoping to launch in around 2 months so if you're ok with it I'll add your project and send you a link when it's live.

**Comment by david-asher** [comment]
Hi Sam, absolutely - I'd be delighted to participate!
