### ISSUE TITLE
fsrpl - Cloud Firestore replication CLI tool

### ISSUE THREAD

**Issue by matsu0228** [firebase/firebaseopensource.com#192]
**Link to project (GitHub)**: 
https://github.com/matsu0228/fsrpl

**Describe the project in 2-3 sentences**: 

This is a CLI tool that enables you to perform the following operations about `Cloud Firestore` easily!
- `dump` and `restore` the data in the specified document as a json file. You can 
- `copy` data under a specified collection to a specific collection in another project.

**Why would Firebase developers be interested in this project?**

It is possible to backup firestore's data in the `Firebase CLI`, but you will need to write a script to restore only specific data or to copy it to another collection.

With using `fsrpl`, you can do these operations easily.
- `copy`: In case of a destructive schema change, you may want to leave the existing data as it is and put the data in the new schema at the destination of the renamed collection. This is when you can use this tool.
- `dump` & `restore`: You can prepare test data easily by dumping specific data in the production environment as a json file and restoring it in the test environment. Of course, it can also be restored to FirestoreEmulator.

This tool can be easily installed with `Homebrew` for Mac users and `go get` command (And of course, in a CI environment.) for those who can use Go.

**Have you added a `.opensource/project.json` file to your site**: 

Yes

**Comment by samtstern** [comment]
@matsu0228 very cool project, just added it to the site!  You should see it appear within 24 hours.  Also I love the logo.

**Comment by samtstern** [comment]
@matsu0228 we're making a new site similar to firebaseopensource.com but for all of Google. So it would be one place with projects like yours plus projects from Flutter, Angular, Android, etc.

Would it be ok if I included this project on that site? We're hoping to launch in around 2 months so if you're ok with it I'll add your project and send you a link when it's live.

**Comment by matsu0228** [comment]
OK,
I'm looking forward to seeing that site!
