### ISSUE TITLE
Firestore ORM in Python

### ISSUE THREAD

**Issue by AxeemHaider** [firebase/firebaseopensource.com#197]
**Link to project (GitHub)**: https://github.com/octabytes/fireo

**Describe the project in 2-3 sentences**: A modern and simplest convenient ORM package in Python. FireO is specifically designed for the Google's Firestore, it's more than just ORM. It implements validation, type checking, relational model logic and much more facilities.

**Why would Firebase developers be interested in this project?**: Because it make life easier for python developer how are using Firestore in there projects

**Have you added a `.opensource/project.json` file to your site**: No

**Comment by samtstern** [comment]
@AxeemHaider this looks like a great project and I am happy to add it to the site!  Just add an `.opensource/project.json` file to your repo.  For some examples you can look at the repos of any of the other third-party projects already listed on this site.

**Comment by AxeemHaider** [comment]
Done! `.opensource/project.json` added

**Comment by samtstern** [comment]
@AxeemHaider great! I added your project to the config, you should see it on the site in the next 24 hours.
