### ISSUE TITLE
moleculer-db-firebase

### ISSUE THREAD

**Issue by Waddah-JD** [firebase/firebaseopensource.com#199]
**Link to project (GitHub)**: 
https://github.com/Waddah-JD/moleculer-db-firebase

**Describe the project in 2-3 sentences**: 
a Firebase 'Cloud Firestore' adapter and service mixin for `Moleculer` DB service

**Why would Firebase developers be interested in this project?**:
this project makes developing microservices with Molecular and Firestore simple, concise and fun,
just plug your Firebase App and start calling services

**Have you added a `.opensource/project.json` file to your site**:
Yes

**Comment by samtstern** [comment]
@Waddah-JD sounds great, happy to add it!

**Comment by samtstern** [comment]
@Waddah-JD you should see your project on the site within 24 hours.
