### ISSUE TITLE
Add Project: Fireschema

### ISSUE THREAD

**Issue by yarnaimo** [firebase/firebaseopensource.com#203]
**Link to project (GitHub)**: https://github.com/yarnaimo/fireschema

**Describe the project in 2-3 sentences**:
Fireschema is strongly typed Firestore framework for TypeScript. It provides type information to nested documents from simple schema, without unsafe type assertions. Also supports security rules generation and guarding HTTPS callable function's request/response data type.

**Why would Firebase developers be interested in this project?**:
Fireschema automatically provides type information to subcollections or parents and you don't need call `withConverter()` or add type annotations every time you refer to them.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by samtstern** [comment]
@yarnaimo this looks great! Happy to add it to the site. Would you also like me to add it to https://devlibrary.withgoogle.com ?

**Comment by samtstern** [comment]
I've added this to the config and your project should appear on firebaseopensource.com in the next 24h, let me know if you want to be on devlibrary as well!
