### ISSUE TITLE
Add firebase manager

### ISSUE THREAD

**Issue by Prajwal-Koirala** [firebase/firebaseopensource.com#214]
https://github.com/complexorganizations/firestore-manager

**Comment by samtstern** [comment]
@Prajwal-Koirala if you add the proper `.opensource/project.json` file to your repo I'd be happy to add your project!

**Comment by Prajwal-Koirala** [comment]
added

**Comment by samtstern** [comment]
Added your project! It should show up on the site within 24 hours.

**Comment by Prajwal-Koirala** [comment]
Thank you my good sir.

@samtstern
