### ISSUE TITLE
Add FireCMS

### ISSUE THREAD

**Issue by fgatti675** [firebase/firebaseopensource.com#217]
**Link to project (GitHub)**: 
https://github.com/Camberi/firecms

**Describe the project in 2-3 sentences**:
FireCMS is a headless CMS and admin panel based on Firebase, built by developers
for developers. It generates CRUD views based on your configuration. You define
views that are mapped to absolute or relative paths in your Firestore database,
as well as schemas for your entities.
We developed this generic CMS after developing 3 different admin tools for clients and
decided it was time to build something reusable.

**Why would Firebase developers be interested in this project?**:
It allows them to have a backoffice tool in no time. It covers every common basic use case
and it is easily extengable using React to fit every need :)

**Have you added a `.opensource/project.json` file to your site**: 
Yes

**Comment by samtstern** [comment]
@fgatti675 added it! It should appear on the site within 24 hours.

**Comment by fgatti675** [comment]
Awesome thanks!! :)
