### ISSUE TITLE
NGXS Firestore Plugin

### ISSUE THREAD

**Issue by joaqcid** [firebase/firebaseopensource.com#223]
**Link to project (GitHub)**: https://github.com/ngxs-labs/firestore-plugin

**Describe the project in 2-3 sentences**: NGXS Firestore plugin helps you integrate Firestore and NGXS. It uses @angular/fire under the hood and provides a wrapper service with CRUD operations methods and easy integration with NGXS actions. In addition provides tracking of active connections.

**Why would Firebase developers be interested in this project?**: It's an easier way to integrate NGXS and Firebase, and helps you manage connecting query results with NGXS state

**Have you added a `.opensource/project.json` file to your site**: Yes

https://github.com/ngxs-labs/firestore-plugin/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
@joaqcid looks great, happy to add it!

cc @jamesdaniels who will probably think this is cool.

**Comment by samtstern** [comment]
fixed https://github.com/firebase/firebaseopensource.com/commit/c54a2600ccc0e25f8ff80562c151db0a13e6cdb2, you'll be on the site within 24h
