### ISSUE TITLE
Adding: firepl

### ISSUE THREAD

**Issue by kawamataryo** [firebase/firebaseopensource.com#225]
**Link to project (GitHub)**: 
https://github.com/kawamataryo/firepl

**Describe the project in 2-3 sentences**: 
This is a custom REPL to make it easier to use Firestore on Node.js REPL.

**Why would Firebase developers be interested in this project?**: 
- When checking or modifying data in Firestore, you can easily operate it on the terminal without accessing the Firebase console.
- You can skip the steps to use the Firebase Admin SDK with a regular Node.js REPL.
- Top-level await can be used

**Have you added a `.opensource/project.json` file to your site**: 
yes
https://github.com/kawamataryo/firepl/blob/main/.opensource/project.json

Examples:
 - https://github.com/invertase/react-native-firebase/blob/master/.opensource/project.json
 - https://github.com/sgarciac/fuego/blob/master/.opensource/project.json
 - https://github.com/firebase/emberfire/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
@kroikie or maybe @abeisgoat who is looking after this repo these days?

**Comment by kroikie** [comment]
This looks pretty cool, happy to add it.
