### ISSUE TITLE
Firelord

### ISSUE THREAD

**Issue by tylim88** [firebase/firebaseopensource.com#234]
**Link to project (GitHub)**: https://github.com/tylim88/firelord

**Describe the project in 2-3 sentences**: Write truly scalable firestore code with complete deep typing firestore wrapper, no more typing hell in your firestore code.

**Why would Firebase developers be interested in this project?**: 
1, probably the only wrapper that deals with virtually any complex data type (nested array/object(map) type)
2. type everything:
 - document path type, collection path type, collection group path type and auto-generate sub collection path type
 - typed all Firestore.FieldValue: arrayUnion, arrayRemove, serverTimestamp and increment
 - safeguard against orderBy limitation.
 - prevent users from writing unnecessary values (especially undefined because of typescript partial member type) 
  - prevent users from writing stranger members into the database.
3. easiest to set up
4. it is virtually impossible to make any typing mistake with the wrapper.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@tylim88 added it! It should appear on the site within 24 hours.
