### ISSUE TITLE
A package for simplifying deployment of Golang Cloud Functions

### ISSUE THREAD

**Issue by schmorrison** [firebase/firebaseopensource.com#240]
**Link to project (GitHub)**: https://github.com/cleanflo/firebase-fx

**Describe the project in 2-3 sentences**: A wrapper for Cloud Functions that exposes a "shared endpoint" and outputs a bash script for function deployment. The API is inspired by the NodeJS firebase-functions package. 

**Why would Firebase developers be interested in this project?**: The workflow for deploying Cloud Functions in golang can be quite a headache, this package means to reduce the LoC required to deploy a Go application.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@schmorrison added it! It should appear on the site within 24 hours.

**Comment by thatfiredev** [comment]
It is live: https://firebaseopensource.com/projects/cleanflo/firebase-fx/
