### ISSUE TITLE
SwiftyInAppMessaging

### ISSUE THREAD

**Issue by fumito-ito** [firebase/firebaseopensource.com#250]
**Link to project (GitHub)**: https://github.com/fumito-ito/SwiftyInAppMessaging

**Describe the project in 2-3 sentences**: The easiest way to use your customized view and InAppMessaging default view. SwiftyInAppMessaging allows you to use your customized message view and FIAM default views easily.

**Why would Firebase developers be interested in this project?**: There are complex steps to use customized message views on Firebase In-App Messaging. SwiftyInAppMessaging allows developers to use easily customized message views and FIAM default views. 

**Have you added a `.opensource/project.json` file to your site**: YES

**Comment by thatfiredev** [comment]
@fumito-ito added it! It should appear on the site within 24 hours.

**Comment by thatfiredev** [comment]
This is now live: https://firebaseopensource.com/projects/fumito-ito/SwiftyInAppMessaging
