### ISSUE TITLE
PyFireSQL

### ISSUE THREAD

**Issue by bennycheung** [firebase/firebaseopensource.com#254]
**Link to project (GitHub)**:  https://github.com/bennycheung/PyFireSQL

**Describe the project in 2-3 sentences**: 
PyFireSQL is a SQL-like programming interface to query Cloud Firestore collections using Python. We can use SQL-like statements to perform the data extraction, which is both formal and reusable.

**Why would Firebase developers be interested in this project?**:
The combination of Python and [lark](https://lark-parser.readthedocs.io/en/latest/) parser generator is more appropriate for backend processing and analysis toolchain. In particular, the extracted data can be directly imported into downstream Pandas Dataframe post-processing will be an extremely valuable prospect.

> Read the companion article [FireSQL in Python](https://bennycheung.github.io/firesql-in-python) for more details.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@bennycheung added it! It should appear on the site within 24 hours.
