### ISSUE TITLE
FireCall

### ISSUE THREAD

**Issue by tylim88** [firebase/firebaseopensource.com#259]
**Link to project (GitHub)**: https://github.com/tylim88/FireCall

**Describe the project in 2-3 sentences**:  Helper Function to write easier and safer Firebase onCall function

**Why would Firebase developers be interested in this project?**: 

FireCall standardizes how functions should handle:

- Unauthorized Authentication Error
- Unknown Error
- Invalid Request Data Error (ZodError)
- Invalid Response Data Error (ZodError)
- Validate Request Data With Zod
- Validate Response Data With Zod
- error logging (only log the error, does not save the error into a file)

Ensuring:

- always use standard HTTPS Error
- end point data type safety for both ends
- same function name for both ends.

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@tylim88 Thanks! Added the project to the site, should be live within 24 hours.
