### ISSUE TITLE
FireCaller

### ISSUE THREAD

**Issue by tylim88** [firebase/firebaseopensource.com#261]
**Link to project (GitHub)**: https://github.com/tylim88/FireCaller

**Describe the project in 2-3 sentences**: 
🔥Write callable functions systematically like a Firelord. No more chaotic error handling, no more unsafe endpoint data type, no more messy validation. Be the Master of Fire you always wanted to be.

**Why would Firebase developers be interested in this project?**:  

this is the twin library of FireCall https://github.com/firebase/firebaseopensource.com/issues/259

FireCaller request and FireCall response

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@tylim88 Thanks! Added in https://github.com/firebase/firebaseopensource.com/commit/7d614ded81572651c7405b931e5464022baa0ae4

Should be live within 24h.
