### ISSUE TITLE
FireSageJS

### ISSUE THREAD

**Issue by tylim88** [firebase/firebaseopensource.com#267]
**Link to project (GitHub)**: https://github.com/tylim88/FireSageJS

**Describe the project in 2-3 sentences**: Extreme Type Safe For Realtime Database Web, Write RTDB Code That Stand The Test Of Time

**Why would Firebase developers be interested in this project?**: the same reason as https://github.com/firebase/firebaseopensource.com/issues/258 but for RTDB

it is also possibly the only RTDB type-safe wrapper in existence

**Have you added a `.opensource/project.json` file to your site**: Yes

**Comment by thatfiredev** [comment]
@tylim88 Happy to add it to the site.

Btw, don't forget to submit it to DevLibrary as well, I see you already have some submissions there.
We are currently evaluating wether it's worth keeping firebaseopensource.com now that DevLibrary exists.
