### ISSUE TITLE
FlutterFIre version number badges don't show up

### ISSUE THREAD

**Issue by kroikie** [firebase/firebaseopensource.com#56]
None of the FlutterFire version badges show up.

Eg: The Firestore plugin version badge:
https://img.shields.io/pub/v/cloud_firestore.svg

<img alt="firestore version badge" src="https://img.shields.io/pub/v/cloud_firestore.svg"/>

I'm not sure if GitHub likes the ![alt][src] format.

**Comment by samtstern** [comment]
Fixed by https://github.com/firebase/firebaseopensource.com/commit/23ef7b2fe7d1a2ea835456c9301e2c774253e390
