### ISSUE TITLE
Add metadata for social media

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebaseopensource.com#61]
I suggest adding meta tags like [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup) and [OpenGraph](http://ogp.me/), so we can have a nice preview when sharing links on Social Media.

**Comment by samtstern** [comment]
@rosariopfernandes that's a good idea, thanks!

**Comment by samtstern** [comment]
Here's how it looks now:

![image](https://user-images.githubusercontent.com/8466666/45128476-1810c200-b133-11e8-8a68-6d2e0e11c58a.png)

**Comment by rosariopfernandes** [comment]
Looks great! :smiley: Great work
