### ISSUE TITLE
Contents dropdown is misplaced in some projects

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebaseopensource.com#78]
**What Happened?**
The "contents dropdown" is displayed in different positions depending on the structure of each project's content file. Apparently, it places itself before the first `h2` from the content file, but some projects have their first `h2` way bellow while others have it right on top.

**What Did You Expect to Happen**
I expected the contents dropdown to be shown on top of the page for every project. I believe this would make it easier to find.

**Screenshot (If Applicable)**
The [Firebase Android SDK](https://firebaseopensource.com/projects/firebase/firebase-android-sdk/) is an example of a project that has the content dropdown misplaced:
![fosdc_android_sdk](https://user-images.githubusercontent.com/16766726/46769947-bfae8080-cced-11e8-91d2-0def267945b2.png)

Here's how I expected it to look:
![fosdc_firextensions](https://user-images.githubusercontent.com/16766726/46769954-cf2dc980-cced-11e8-8d22-9cf168cae34d.png)

**Comment by samtstern** [comment]
@rosariopfernandes thanks for pointing this out!  You're totally correct as to how we place it.  And I like your suggestion of where to move it.
