### ISSUE TITLE
Add @react-firebase ?

### ISSUE THREAD

**Issue by rakannimer** [firebase/firebaseopensource.com#81]
Hey ! 

Thanks for building and maintaining this repo 😄 

I built [@react-firebase](https://react-firebase-js.com) to make it easier to integrate Firebase in any React app. 

It works and was designed to work with firebase web, react-native-firebase and firebase-admin !

The supported firebase services are : 

- [Realtime Database](https://react-firebase-js.com/docs/react-firebase-realtime-database/getting-started)

- [Firestore](https://react-firebase-js.com/docs/react-firestore-database/getting-started)

- [Auth](https://react-firebase-js.com/docs/react-firebase-auth/getting-started)

I use it regularly and am committed to keeping it highly-tested and bug-free.

Repo : https://github.com/rakannimer/react-firebase

Docs : https://react-firebase-js.com/

Cheers !

**Comment by samtstern** [comment]
@rakannimer happy to add it!  You'll need to add a `.opensource/project.json` file to your repo, see this one for a good example:
https://github.com/rosariopfernandes/fireXtensions/blob/master/.opensource/project.json

Once you've done that, I will add you to our crawl list.

**Comment by rakannimer** [comment]
Thanks @samtstern for your quick response :) 

I added the `.opensource/project.json` file to the repo. 
You can find it here : https://github.com/rakannimer/react-firebase/blob/master/.opensource/project.json

Please let me know, if I missed something.

Cheers !

**Comment by samtstern** [comment]
@rakannimer added!  Should show up on the site in 30m or less.

**Comment by samtstern** [comment]
https://firebaseopensource.com/projects/rakannimer/react-firebase/

Seems like it's live, although not sure it's being properly static generated.

**Comment by samtstern** [comment]
Fixed, now it's super fast.

**Comment by rakannimer** [comment]
Awesome ! Thanks a lot :)
