### ISSUE TITLE
Include FireDrill in Open Source Web projects

### ISSUE THREAD

**Issue by scottlepp** [firebase/firebaseopensource.com#84]
Please consider adding FireDrill.  It has lots of useful features for Firebase, and examples of using the web api.

https://github.com/scottlepp/fire-drill

**Comment by samtstern** [comment]
@scottlepp happy to add it!  You'll need to add the `.opensource/project.json` on your side first. 

Here's a super simple example:
https://github.com/jsayol/FireSQL/blob/master/.opensource/project.json

And a more advanced one:
https://github.com/firebase/FirebaseUI-Android/blob/master/.opensource/project.json

**Comment by samtstern** [comment]
Oh and make sure to add a "description" to your repo on GitHub!

**Comment by samtstern** [comment]
@scottlepp looks good to me!

I'm working through some deployment issues for the site right now but your page should be up by the end of the day
