### ISSUE TITLE
Add `react-firebase-hooks`

### ISSUE THREAD

**Issue by chrisbianca** [firebase/firebaseopensource.com#95]
**Link to project (GitHub)**: https://github.com/CSFrequency/react-firebase-hooks

**Describe the project in 2-3 sentences**: A set of reusable React Hooks for Firebase, covering Auth, Cloud Firestore, Cloud Storage and Realtime Database.  The library simplifies the use of common Firebase operations when using React.

**Why would Firebase developers be interested in this project?**: There has been a lot of hype around React Hooks, but this hype merely reflects that there are obvious real world benefits of Hooks to React developers everywhere. This library explores how React Hooks can work to make integration with Firebase even more straightforward than it already is. It takes inspiration for naming from RxFire and is based on an internal library that we had been using in a number of apps prior to the release of React Hooks. The implementation with hooks is 10x simpler than our previous implementation.

**Comment by samtstern** [comment]
@chrisbianca thanks for this contribution!  I added your library, it should show up within 24 hours.

Just curious, how did you hear about firebaseopensource.com?

**Comment by chrisbianca** [comment]
Thanks @samtstern!
I knew about firebaseopensource.com from my time working on React Native Firebase.

**Comment by samtstern** [comment]
https://firebaseopensource.com/projects/csfrequency/react-firebase-hooks/
