### ISSUE TITLE
Please consider adding fuego

### ISSUE THREAD

**Issue by sgarciac** [firebase/firebaseopensource.com#96]
Plase consider including [fuego](https://www.github.com/sgarciac/fuego) to the list of firebase open source projects. Fuego is a command line client for the firestore database.

(I put "Go", and "Admin" in the platforms list of my .opensource/project.json file, I hope its a valid list)

**Comment by samtstern** [comment]
@sgarciac done!  It should show up on the site in about 24 hours.

When it does, it will be here:
https://firebaseopensource.com/projects/sgarciac/fuego
