### ISSUE TITLE
Firebase Realtime Database RecyclerView Pagination

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebaseopensource.com#98]
**Link to project (GitHub)**: https://github.com/patilshreyas/FirebaseRecyclerPagination

**Describe the project in 2-3 sentences**: 
In this project, I implemented support for loading Firebase Realtime Database Query to _RecyclerView_ by loading data in pages. **_FirebaseRecyclerPaginationAdapter_** is built on the top of Android Paging Support Library.

**Why would Firebase developers be interested in this project?**: 
FirebaseUI-Android repository has not such API to implement pagination of Firebase Realtime Database. Many developers who implement Realtime Database may need pagination support due to the large database. But there is the unavailability of such API. This project will be useful for many developers.
You can see sample app [`here`](https://github.com/patilshreyas/FirebaseRecyclerPagination/tree/master/app) implemented using Firebase Recycler Pagination Library.

**Comment by samtstern** [comment]
@PatilShreyas happy to add you to the site!

**Comment by samtstern** [comment]
You will need to add a `.opensource` folder with the proper config to your repo

**Comment by PatilShreyas** [comment]
Thanks for your response ! 
I will do it and will tell you.

**Comment by PatilShreyas** [comment]
Can we make this feature available in FirebaseUI-Android repository ?

**Comment by samtstern** [comment]
Closed by #99

**Comment by samtstern** [comment]
@PatilShreyas if you want to open an issue on FirebaseUI-Android I am happy to discuss it!  It would depend on the details and tradeoffs of your implementation.
